AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 5 #change as per training requirements
CLASSES: 2 #healty image and non healthy image
WEIGHTS: imagenet
LEARNING_RATE: 0.01